### ISSUE TITLE
Fix image responsiveness

### ISSUE THREAD

**Issue by techieeliot** [techieeliot/hacktoberfest-demo#5]
![image](https://user-images.githubusercontent.com/19453294/95006707-b3074f00-05cc-11eb-8197-60eb701ac240.png)

**Comment by trivedidhruvil9** [comment]
Hey, i will make the image reponsive !!

I have one request, can you add "hacktoberfest" label to the repo, otherwise my pull request won't be eligible!!

regardless, i will make it responsive!

Thanks

**Comment by techieeliot** [comment]
@trivedidhruvil9 The hacktoberfest topic is in the repo already. Thanks for contributing on two issues. 

<img width="346" alt="Screen Shot 2020-10-05 at 8 08 28 AM" src="https://user-images.githubusercontent.com/19453294/95086770-7e87b600-06e6-11eb-8235-369384911c8a.png">
