### ISSUE TITLE
Add a footer with information about freeCodeCamp Jackson

### ISSUE THREAD

**Issue by techieeliot** [techieeliot/hacktoberfest-demo#7]
Contact @techieeliot  for information.

[The meetup page ](https://www.meetup.com/freeCodeCamp-Jackson-Mississippi-Meetup-Group/)

**Comment by pisethchhom** [comment]
hello i would like to contribute to this issue

**Comment by techieeliot** [comment]
Hey @pisethchhom! I've assigned you to this task. I need to clean up the repo. Please allow me to fix it on my end before forking and cloning the repo.

**Comment by pisethchhom** [comment]
> Hey @pisethchhom! I've assigned you to this task. I need to clean up the repo. Please allow me to fix it on my end before forking and cloning the repo.

sure, please let me know after that

**Comment by techieeliot** [comment]
Ok, please clone the repo @pisethchhom. 

Can you build the mobile and desktop versions to look like this:

* please note that I forgot to include the Copyright symbol in the mobile version
<img width="279" alt="Screen Shot 2020-10-06 at 12 31 23 AM" src="https://user-images.githubusercontent.com/19453294/95162812-154a8600-076c-11eb-9574-77b0216a143c.png">
<img width="1440" alt="Screen Shot 2020-10-06 at 12 36 05 AM" src="https://user-images.githubusercontent.com/19453294/95162814-167bb300-076c-11eb-8f69-a828934f9dfa.png">

**Comment by pisethchhom** [comment]
> Ok, please clone the repo @pisethchhom.
> 
> Can you build the mobile and desktop versions to look like this:
> 
> * please note that I forgot to include the Copyright symbol in the mobile version
> 
> <img alt="Screen Shot 2020-10-06 at 12 31 23 AM" width="279" src="https://user-images.githubusercontent.com/19453294/95162812-154a8600-076c-11eb-9574-77b0216a143c.png">
> 
> <img alt="Screen Shot 2020-10-06 at 12 36 05 AM" width="1440" src="https://user-images.githubusercontent.com/19453294/95162814-167bb300-076c-11eb-8f69-a828934f9dfa.png">

yes noted thank you :)
